<?php

namespace App\Console\Commands;

use App\BookingStatus;
use App\Models\Booking;
use App\Models\Exhibition;
use App\Models\User;
use Illuminate\Console\Command;

class CreateTestBooking extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'booking:create-test
                            {--exhibition=1 : The exhibition ID}
                            {--stalls=* : Stall numbers (e.g., --stalls=101 --stalls=102)}
                            {--area=96 : Total area in sq m}
                            {--price=5000 : Price per sq m}
                            {--discount=10 : Discount percentage}
                            {--space-type=standard : Space type (standard or raw)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a test booking that is approved by both admin levels and ready for payment';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('Creating test booking...');

        // Get exhibition
        $exhibitionId = $this->option('exhibition');
        $exhibition = Exhibition::find($exhibitionId);

        if (! $exhibition) {
            $this->error("Exhibition with ID {$exhibitionId} not found!");

            return self::FAILURE;
        }

        // Get admin users
        $admin = User::where('role', 'admin')->first();
        $superAdmin = User::where('role', 'super_admin')->first();

        if (! $admin) {
            $this->error('No admin user found! Please create an admin user first.');

            return self::FAILURE;
        }

        if (! $superAdmin) {
            $this->error('No super admin user found! Please create a super admin user first.');

            return self::FAILURE;
        }

        // Get stalls or use default
        $stalls = $this->option('stalls');
        if (empty($stalls)) {
            $stalls = ['101']; // Default stall
        }

        // Get pricing details
        $totalArea = (float) $this->option('area');
        $pricePerSqm = (float) $this->option('price');
        $discountPercentage = (float) $this->option('discount');

        // Calculate pricing
        $totalPrice = $totalArea * $pricePerSqm;
        $discountAmount = $totalPrice * ($discountPercentage / 100);
        $priceAfterDiscount = $totalPrice - $discountAmount;
        $gstAmount = $priceAfterDiscount * 0.18; // 18% GST
        $totalWithGst = $priceAfterDiscount + $gstAmount;

        // Get space type
        $spaceType = $this->option('space-type') ?? 'standard';

        // Create booking (booking_code will be auto-generated by the model)
        $booking = Booking::create([
            'exhibition_id' => $exhibition->id,
            'brand_name' => 'Test Company Pvt Ltd',
            'contact_person' => 'Test User',
            'phone_code' => '+91',
            'phone_number' => '7874949091',
            'email' => 'test@example.com',
            'city' => 'Surat',
            'gst_number' => '24AAAAA0000A1Z5',
            'product_profile' => ['4-wheelers', '2-wheelers'],
            'has_exhibited_before' => true,
            'participation_years' => ['2023', '2024'],
            'is_sgcci_member' => true,
            'membership_type' => 'gold',
            'space_type' => $spaceType,
            'selected_stalls' => $stalls,
            'status' => BookingStatus::PaymentPending,
            'admin_approved_by' => $admin->id,
            'admin_approved_at' => now()->subDays(2),
            'super_admin_approved_by' => $superAdmin->id,
            'super_admin_approved_at' => now()->subDay(),
            'payment_link_sent_at' => now(),
            'payment_due_at' => now()->addDays(7),
        ]);

        // Override the total amount to ₹1.00 for testing
        $booking->update([
            'total_with_gst' => 1.00,
            'payment_link' => route('payment.initiate', $booking->booking_code),
        ]);

        $this->newLine();
        $this->info('✅ Test booking created successfully!');
        $this->newLine();

        // Display booking details
        $this->table(
            ['Field', 'Value'],
            [
                ['Booking Code', $booking->booking_code],
                ['Exhibition', $exhibition->title],
                ['Status', $booking->status->label()],
                ['Contact Person', $booking->contact_person],
                ['Email', $booking->email],
                ['Phone', $booking->phone_code.' '.$booking->phone_number],
                ['Selected Stalls', implode(', ', $booking->selected_stalls)],
                ['Total Area', $booking->total_area.' sq m'],
                ['Price per sq m', '₹'.number_format($booking->price_per_sqm, 2)],
                ['Total Price', '₹'.number_format($booking->total_price, 2)],
                ['Discount ('.$booking->discount_percentage.'%)', '₹'.number_format($booking->discount_amount, 2)],
                ['GST (18%)', '₹'.number_format($booking->gst_amount, 2)],
                ['Total with GST', '₹'.number_format($booking->total_with_gst, 2)],
                ['Admin Approved By', $admin->name.' ('.$booking->admin_approved_at->format('Y-m-d H:i').')'],
                ['Super Admin Approved By', $superAdmin->name.' ('.$booking->super_admin_approved_at->format('Y-m-d H:i').')'],
                ['Payment Due Date', $booking->payment_due_at->format('Y-m-d H:i')],
            ]
        );

        $this->newLine();
        $this->info('🔗 Payment Link:');
        $this->line($booking->payment_link);
        $this->newLine();

        $this->info('💡 To initiate payment, visit:');
        $paymentUrl = route('payment.initiate', $booking->booking_code);
        $this->line($paymentUrl);

        return self::SUCCESS;
    }
}
